### ISSUE TITLE
No styles with Vite and TailwindCSS

### ISSUE THREAD

**Issue by valtism** [zenclabs/reactpreview#29]
**Describe the bug**
When using tailwind and vite, the preview opens but doesn't have any styles.

**To Reproduce**
Try running this project I'm working on https://github.com/valtism/music-list

I think that this may be because Vite doesn't really produce an output css file. It takes the inputs and processes them with postCSS, but then hides the output somewhere that is still available in dev mode.

**Desktop (please complete the following information):**
 - OS: macOS
 - Extension version: 0.2.2

**Comment by fwouts** [comment]
Thanks for the bug report!

I will investigate tomorrow but in the meantime, just pointing out that it might just be that you need a Wrapper.tsx file that imports your index.css. See https://reactpreview.com/usage for more details 🙂

**Comment by valtism** [comment]
Gave it a shot, but didn't work out

```
// __reactpreview__:Wrapper.tsx

import React from "react";
import "./index.css";

interface WrapperProps {
  children: React.ReactNode;
}

export default function Wrapper({ children }: WrapperProps) {
  return <>{children}</>;
}
```

Also, when setting this up I managed to trigger the bug of a process being spawned and chewing 100% CPU that I had to track down and kill again.

**Comment by valtism** [comment]
Well I found out I made a typo in the name, and was also doing a default export (in an attempt to satisfy TypeScript).

In the end I have this:

```tsx
// __reactpreview__/Wrapper.tsx
import React from "react";
import "../global-stylesheet.css";

export const Wrapper: React.FC = ({ children }) => <>{children}</>;
```

And when I open react preview, it just loads indefinitely. No console output or anything.

**Comment by valtism** [comment]
Oops, just realised I was not importing the example `global-stylesheet.css`. Fixed that and still have the indefinite load problem. No output in the extension host output.

**Comment by valtism** [comment]
The funny thing is, is that I can import `index.css` directly in a component that I am previewing and it works. I can use the wrapper when it does not import `index.css`, and it works (without styles). I can even use the wrapper without an import, wrapping the previewing component that does import, and it works. 

The only time it hangs is when I add the css import in the wrapper.

**Comment by fwouts** [comment]
Fascinating. Thanks for debugging this, it should make my life easier to fix it. Remind me to give you a free premium license when the premium features come out 😉

**Comment by fwouts** [comment]
Hey @valtism, I've just released v0.2.3, which should work well with your repo. Thanks again, it was instrumental in finding some pretty complex bugs!

**Comment by valtism** [comment]
No luck :( I'm running 0.2.3 but still get the same issue as last time.

Try it with my repo linked above. Again, here's the Wrapper I'm using:

```tsx
// __reactpreview__/Wrapper.tsx
import React from "react";
import "index.css";

interface WrapperProps {
  children: React.ReactNode;
}

export function Wrapper({ children }: WrapperProps) {
  return children;
}
```

**Comment by fwouts** [comment]
Weird, I did get your project working on mine!

Two possible explanations come to mind:
- your CSS import may be incorrect (shouldn't it be `../index.css`?)
- you may (hopefully not) need to delete `node_modules/.vite`, where cached dependencies are stored

You can also simply do `export Wrapper = React.Fragment` by the way :) (I'll probably change it so you don't need to explicitly create it in the future).

**Comment by valtism** [comment]
Ah, that's it!

This is what worked:
```tsx
import React from "react";
import "../index.css";

export const Wrapper = React.Fragment;
```
